/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package choose_from;

import java.awt.GraphicsEnvironment;
import java.io.Console;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Nikorobos
 */
public class ChooseFrom extends javax.swing.JFrame {

    /**
     * Creates new form ChooseFrom
     */
    public ChooseFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fysFile = new javax.swing.JButton();
        fysManual = new javax.swing.JButton();
        fysCI = new javax.swing.JButton();
        dksFile = new javax.swing.JButton();
        dksManual = new javax.swing.JButton();
        dksCI = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electronic draws");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));

        jButton8.setBackground(new java.awt.Color(127, 126, 66));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Conduct an electronic draw");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(221, 221, 221));

        fysFile.setBackground(new java.awt.Color(227, 174, 0));
        fysFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fysFile.setForeground(new java.awt.Color(0, 0, 0));
        fysFile.setText("<html>Fisher-Yates shuffle<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input via a file</html>");
        fysFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fysFileActionPerformed(evt);
            }
        });

        fysManual.setBackground(new java.awt.Color(255, 229, 142));
        fysManual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fysManual.setForeground(new java.awt.Color(0, 0, 0));
        fysManual.setText("<html>Fisher-Yates shuffle<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type-in input</html>");
        fysManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fysManualActionPerformed(evt);
            }
        });

        fysCI.setBackground(new java.awt.Color(191, 213, 148));
        fysCI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fysCI.setForeground(new java.awt.Color(0, 0, 0));
        fysCI.setText("<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fisher-Yates shuffle<br/>type-in input - command line</html>");
        fysCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fysCIActionPerformed(evt);
            }
        });

        dksFile.setBackground(new java.awt.Color(155, 111, 54));
        dksFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dksFile.setForeground(new java.awt.Color(0, 0, 0));
        dksFile.setText("<html>Durstenfeld-Knuth shuffle<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input via a file</html>");
        dksFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dksFileActionPerformed(evt);
            }
        });

        dksManual.setBackground(new java.awt.Color(113, 141, 54));
        dksManual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dksManual.setForeground(new java.awt.Color(0, 0, 0));
        dksManual.setText("<html>Durstenfeld-Knuth shuffle<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type-in input</html>");
        dksManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dksManualActionPerformed(evt);
            }
        });

        dksCI.setBackground(new java.awt.Color(58, 71, 27));
        dksCI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dksCI.setForeground(new java.awt.Color(0, 0, 0));
        dksCI.setText("<html>&nbsp;&nbsp;&nbsp;&nbsp;Durstenfeld-Knuth shuffle<br/>&nbsp;&nbsp;type-in input - command line</html>");
        dksCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dksCIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dksFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fysFile, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fysManual, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dksManual, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dksCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fysCI, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fysCI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(fysFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fysManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dksFile, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(dksCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dksManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void fysFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fysFileActionPerformed
        new ShuffleEng();
        
    }//GEN-LAST:event_fysFileActionPerformed

    private void dksFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dksFileActionPerformed
        new Knuth();
    }//GEN-LAST:event_dksFileActionPerformed

    private void dksManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dksManualActionPerformed
        new KnuthManulEng();
    }//GEN-LAST:event_dksManualActionPerformed

    private void fysManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fysManualActionPerformed
        new ShuffleManualEng();
    }//GEN-LAST:event_fysManualActionPerformed

    private void fysCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fysCIActionPerformed
        try {
            
            String dir = System.getProperty("user.dir");
            File file = new File("fysmi.exe");
            File dirOf = new File(dir,file.separator);

            ProcessBuilder p = new ProcessBuilder("cmd", "/c","start",file.toString());
            p.directory(dirOf);
            p.start();
            
        } catch (IOException ex) {
            Logger.getLogger(ChooseFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_fysCIActionPerformed

    private void dksCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dksCIActionPerformed
       try {
             String dir = System.getProperty("user.dir");
            File file = new File("dksmi.exe");
            File dirOf = new File(dir,file.separator);

            ProcessBuilder p = new ProcessBuilder("cmd", "/c","start",file.toString());
            p.directory(dirOf);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(ChooseFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_dksCIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dksCI;
    private javax.swing.JButton dksFile;
    private javax.swing.JButton dksManual;
    private javax.swing.JButton fysCI;
    private javax.swing.JButton fysFile;
    private javax.swing.JButton fysManual;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
